List eventsWithLocation = [
  {
    "id": 0,
    "description": "Picnic at the park",
    "interests": [0],
    "members": [0],
    "title": "Picnic",
    "locationBased": true,
    "latitude": 65.012615,
    "longitude": 25.412615,
    "hostID": 0,
    "maxPeople": 10,
    "minPeople": 0,
    "startEvent": "2022-04-25T11:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 1,
    "description": "Tournamnet for everyone interested",
    "interests": [0],
    "members": [0],
    "title": "Football Tournament",
    "locationBased": true,
    "latitude": 65.022615,
    "longitude": 25.481453,
    "hostID": 1,
    "maxPeople": 8,
    "minPeople": 0,
    "startEvent": "2022-04-14T08:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 2,
    "description": "Cooking at the park with strangers",
    "interests": [0],
    "members": [0],
    "title": "Cooking at the park",
    "locationBased": true,
    "latitude": 25.482453,
    "longitude": 25.482453,
    "hostID": 2,
    "maxPeople": 0,
    "minPeople": 24,
    "startEvent": "2022-22-03T14:34:59.506Z",
    "hasStarted": true
  },
  {
    "id": 3,
    "description": "Lets play airsoft for fun",
    "interests": [0],
    "members": [0],
    "title": "Airsoft",
    "locationBased": true,
    "latitude": 65.012315,
    "longitude": 25.492615,
    "hostID": 0,
    "maxPeople": 10,
    "minPeople": 0,
    "startEvent": "2022-04-25T11:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 4,
    "description": "Swimming with people who has interested",
    "interests": [0],
    "members": [0],
    "title": "Swimming",
    "locationBased": true,
    "latitude": 65.025615,
    "longitude": 25.421453,
    "hostID": 1,
    "maxPeople": 8,
    "minPeople": 0,
    "startEvent": "2022-04-14T08:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 5,
    "description": "Lets partyyy",
    "interests": [0],
    "members": [0],
    "title": "Party at the beach",
    "locationBased": true,
    "latitude": 25.512453,
    "longitude": 25.502453,
    "hostID": 2,
    "maxPeople": 0,
    "minPeople": 24,
    "startEvent": "2022-22-03T14:34:59.506Z",
    "hasStarted": true
  }
];

const allEvents = [
  {
    "id": 0,
    "description": "Lets play games from home together online",
    "interests": [0],
    "members": [0],
    "title": "Just Playing home",
    "locationBased": false,
    "latitude": 0,
    "longitude": 0,
    "hostID": 0,
    "maxPeople": 10,
    "minPeople": 0,
    "startEvent": "2022-04-25T11:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 1,
    "description":
        "Swimming with people who has interested, Lets meet at the beach and then we go swimming and sauna is warming up of course. Wlcome!",
    "interests": [0],
    "members": ['0', '1', '2', '3', '4', '5'],
    "title": "Swimming",
    "locationBased": true,
    "latitude": 65.025615,
    "longitude": 25.421453,
    "hostID": 1,
    "maxPeople": 8,
    "minPeople": 0,
    "startEvent": "2022-04-14T08:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 2,
    "description": "Lets partyyy",
    "interests": [0],
    "members": [0],
    "title": "Party at the beach",
    "locationBased": true,
    "latitude": 25.512453,
    "longitude": 25.502453,
    "hostID": 2,
    "maxPeople": 0,
    "minPeople": 24,
    "startEvent": "2022-22-03T14:34:59.506Z",
    "hasStarted": true
  },
  {
    "id": 3,
    "description": "Picnic at the park",
    "interests": [0],
    "members": [0],
    "title": "Picnic",
    "locationBased": true,
    "latitude": 65.012615,
    "longitude": 25.412615,
    "hostID": 0,
    "maxPeople": 10,
    "minPeople": 0,
    "startEvent": "2022-04-25T11:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 4,
    "description": "Tournamnet for everyone interested",
    "interests": [0],
    "members": [0],
    "title": "Football Tournament",
    "locationBased": true,
    "latitude": 65.022615,
    "longitude": 25.481453,
    "hostID": 1,
    "maxPeople": 8,
    "minPeople": 0,
    "startEvent": "2022-04-14T08:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 5,
    "description": "Cooking at the park with strangers",
    "interests": [0],
    "members": [0],
    "title": "Cooking at the park",
    "locationBased": true,
    "latitude": 25.482453,
    "longitude": 25.482453,
    "hostID": 2,
    "maxPeople": 0,
    "minPeople": 24,
    "startEvent": "2022-22-03T14:34:59.506Z",
    "hasStarted": true
  },
];

const eventsOfInterestWithLocation = [
  {
    "id": 0,
    "description":
        "Swimming with people who has interested\n, Lets meet at the beach and then we go swimming and sauna is warming up of course. Wlcome!",
    "interests": [0],
    "members": [0],
    "title": "Swimming",
    "locationBased": true,
    "latitude": 65.025615,
    "longitude": 25.421453,
    "hostID": 1,
    "maxPeople": 8,
    "minPeople": 0,
    "startEvent": "2022-04-14T08:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 1,
    "description": "Lets partyyy",
    "interests": [0],
    "members": [0],
    "title": "Party at the beach",
    "locationBased": true,
    "latitude": 25.512453,
    "longitude": 25.502453,
    "hostID": 2,
    "maxPeople": 0,
    "minPeople": 24,
    "startEvent": "2022-22-03T14:34:59.506Z",
    "hasStarted": true
  }
];

const eventsWithNoLocation = [
  {
    "id": 0,
    "description": "CS Tournament for noobs and amateurs",
    "interests": [0],
    "members": [0],
    "title": "CS Tournament",
    "locationBased": false,
    "latitude": 0,
    "longitude": 0,
    "hostID": 0,
    "maxPeople": 10,
    "minPeople": 0,
    "startEvent": "2022-04-28T10:34:59.506Z",
    "hasStarted": false
  },
  {
    "id": 1,
    "description": "Studying together, everyone welcome!",
    "interests": [0],
    "members": [0],
    "title": "Study together",
    "locationBased": false,
    "latitude": 0,
    "longitude": 0,
    "hostID": 1,
    "maxPeople": 8,
    "minPeople": 0,
    "startEvent": "2022-05-14T02:24:59.506Z",
    "hasStarted": false
  }
];
